// <auto-generated />
namespace DemoLab.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingLectures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingLectures));
        
        string IMigrationMetadata.Id
        {
            get { return "201805160554529_AddingLectures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
